---
platform: "linux"
image_resource:
  type: "docker-image"
  source:
    repository: "dpb587/jq"
inputs:
  - name: "env"
  - name: "cf-stack"
  - name: "bosh-stack"
  - name: "infra-stack"
run:
  path: "env/ci/tasks/bosh/cloud-config/execute.sh"
params:
  username: "admin"
  password: "admin"
